[common]
server_addr = ahdx-frp.vip
server_port = 5000
tcp_mux = true
protocol = tcp
user = 1735780681379
token = admin
dns_server = 114.114.114.114

##
[1735782102]
type = tcp
local_ip = 127.0.0.1
local_port = 7890
remote_port = 7881
use_encryption = false
use_compression = false

## ssh
[1735781937]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 7880
use_encryption = false
use_compression = false
